### ISSUE TITLE
Discussion regarding Condor and TDE

### ISSUE THREAD

**Issue by dangeredwolf** [hbang/Condor#4]
_"TweetDeck Enhancer retrieves assets from the owner's website"_

This right here is false, as of the last TWO tweetdeck enhancer releases. 

_"TweetDeck Enhancer...collects analytics. This poses a privacy risk"_

This is ironic, as your own website uses Google Analytics, which tracks your age, gender, general location, ip, device, operating system, browser, and more... I collect way less information than you do, all I collect is the TDE version used, the browser, and the operating system, strictly to help improve the product itself, not for sake of collecting information. Knowing the web browser and operating system you use is not a "privacy risk", any website knows that via navigator.userAgent. I can't even see any ip addresses. I don't even know what IP DDoSed my server. Plus, you can always opt out of information collection, it just takes seconds to do.

_"TweetDeck Enhancer has, in the past, changed majorly every few months or so. I just want something that works."_

I don't have any plans currently to change it drastically any time soon.

_"Condor is licensed under The MIT License. See ."_

I think the link was messed up here.

On a final note, **stop misleading your own users into believing things that are not true.** This is **NEVER** a good thing.

If your users were actually aware, I'm sure many of them would not want to use Condor.

Instead, create more compelling features and end-user advantages to get users. This is how competition is supposed to work, **make yours more interesting, and stand out from mine.**

**Comment by kirb** [comment]
I'm only willing to discuss this if you're going to be mature about it.

**Comment by dangeredwolf** [comment]
That is what I am doing. Did you even read what I wrote?

**Comment by kirb** [comment]
> This right here is false, as of the last TWO tweetdeck enhancer releases.

It took the release of Condor to make it happen.

> This is ironic, as your own website uses Google Analytics

Irrelevant attack, and thanks for the reminder to remove GA since I don't even check it.

> Plus, you can always opt out of information collection, it just takes seconds to do.

If you know how to find privacy.txt and then pop open a js console, sure. It should just work by default. And now, people that _don't_ mind it pulling data from you now have a ~mb of useless files on their disk!

> I don't have any plans currently to change it drastically any time soon.

Sounds good, too late though.

> I think the link was messed up here.

Thanks.

> stop misleading your own users into believing things that are not true

Explain further?

I ignored the privacy issues for several months after (trying to) discuss it with you. People seem happier with an extension that isn't controlled by you. It's not going to change.

**Comment by dangeredwolf** [comment]
> And now, people that don't mind it pulling data from you now have a ~mb of useless files on their disk!

Actually, TweetDeck Enhancer 5.0.6 is smaller than TweetDeck Enhancer 5.0.4, even though 5.0.6 contains all the images and things. In fact, TweetDeck Enhancer 5.0.6 is still smaller than Condor.

**Comment by kirb** [comment]
(Reopening as this is a legitimate discussion.)

**Comment by dangeredwolf** [comment]
Kirb, this was a legitimate discussion to begin with. By the way.

**Comment by kirb** [comment]
It was my mistake and I apologise.

Any responses apart from that about the file size? Which really isn't _that_ important a topic in this context. :/

Not mentioned: Condor significantly cleans up the content script. I've gotten praise from people saying it uses less memory/performs faster.

**Comment by dangeredwolf** [comment]
TDE 5.0.6 actually uses less daemons than previous versions of it. Which is slightly better. However, your content script does not include some of TDE's features such as the navigation drawer. Obviously, adding more features to something isn't going to make it perform better. I think, though, if I change the timing in which a lot of the daemons spawn, it'll help it get going even faster. Either way, it sacrifices a small amount of performance for features and UX.

TweetDeck Enhancer is about the UX. That's why it was ever created, and why it still exists.

**Comment by dangeredwolf** [comment]
I don't think adding a few javascript functions is going to use too much memory, though.

**Comment by dangeredwolf** [comment]
they're separated into daemon-like interfaces that spawn at particular times and sometimes keep going

**Comment by dangeredwolf** [comment]
TDE 5.0.6's TDEinject is divided up into 13 daemons which are run in their own threads. Most run just once, doing specific tasks, such as replacing the favicon (YesFavicon()), changing the sound of notifications (PatchAudio()), or adding the fonts (InjectRobotoFonts()).

**Comment by kirb** [comment]
Daemons - I suppose you mean timers or background scripts?

You're right that it's not on par with TDE yet. I just wanted to get a product out that had sufficient features to be useful enough for now; I spent the whole of Sunday on it (and if you know me, I have a thousand other projects I should be working on). You should revise your use of timers as use of DOMNodeInserted and other events like Condor does.

**Comment by dangeredwolf** [comment]
Yeah the sort of timer things that execute startup activities.

**Comment by dangeredwolf** [comment]
There is room for improvement in TDEinject.js though, for example, there was an unused daemon WaitForTDToConfigureSelf() which I just removed for 5.0.7.

**Comment by dangeredwolf** [comment]
Also yeah, I should probably do that.

**Comment by dangeredwolf** [comment]
My code isn't perfect, and some of my legacy css definitely isn't.

**Comment by dangeredwolf** [comment]
The only thing about DOMNodeInserted is that TweetDeck creates, well, a LOT of nodes. Hopefully it'll perform okay, and based on your Condor work, it should.

**Comment by dangeredwolf** [comment]
Could you unblock me? I just noticed as I was trying to retweet your tweet...

**Comment by Haifisch** [comment]
Guys, can we be sure to hold these types of discussion somewhere other than GitHub, this doesn't seem to be productive towards either projects and really doesn't need to be documented under this repo as an "issue", it just seems personal imo. Also, just a suggestion to Ryan, try to keep your comment rate to a minimum as anybody watching this repo will recieve an email and it tends to get a little spammy (spam, spam, gimmie the spam).
